language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - pip install -r test-requirements.txt --use-mirrors
    - python setup.py develop
script: make coveralls
notifications:
    email: fabien.marty@gmail.com
services:
  - redis-server
